name: Run Tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install playwright pytest-html

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run tests (with logs, traces, HTML)
        run: |
          pytest -v -s \
          --log-cli-level=INFO \
          --tracing=on \
          --html=report.html --self-contained-html
          --video=on --screenshot=only-on-failure

      - name: Upload reports & traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            report.html
            test-results/